package httpapi
import ("encoding/json";"net/http";"strings";"time";"github.com/google/uuid";"golang.org/x/crypto/bcrypt";"auction/backend/internal/auth";"auction/backend/internal/bid";"auction/backend/internal/store")
type API struct { Store *store.Store; Auth *auth.Service; Bids *bid.Engine }
func (a *API) Routes() http.Handler { m:=http.NewServeMux(); m.HandleFunc("/healthz",func(w http.ResponseWriter,_ *http.Request){w.WriteHeader(200)}); m.HandleFunc("/auth/register",a.register); m.HandleFunc("/auth/login",a.login); m.Handle("/auctions",a.Auth.Middleware(http.HandlerFunc(a.auctions))); m.Handle("/auctions/",a.Auth.Middleware(http.HandlerFunc(a.auction))); return m }
func (a *API) register(w http.ResponseWriter,r *http.Request) {
	var in struct{ Email, Password string }; if json.NewDecoder(r.Body).Decode(&in)!=nil || !strings.Contains(in.Email,"@") || len(in.Password)<12 { http.Error(w,"invalid credentials",400); return }
	hash,err:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost); if err!=nil { http.Error(w,"server error",500); return }
	id:=uuid.NewString(); if err=a.Store.CreateUser(r.Context(),id,strings.ToLower(strings.TrimSpace(in.Email)),string(hash));err!=nil { http.Error(w,"registration failed",409); return }; tok,err:=a.Auth.Issue(id);if err!=nil{http.Error(w,"server error",500);return}; json.NewEncoder(w).Encode(map[string]string{"token":tok})
}
func (a *API) login(w http.ResponseWriter,r *http.Request) {
	var in struct{ Email, Password string }; if json.NewDecoder(r.Body).Decode(&in)!=nil { http.Error(w,"invalid credentials",400); return }; id,hash,err:=a.Store.UserPassword(r.Context(),strings.ToLower(strings.TrimSpace(in.Email)));if err!=nil||bcrypt.CompareHashAndPassword([]byte(hash),[]byte(in.Password))!=nil { http.Error(w,"invalid credentials",401);return }; tok,err:=a.Auth.Issue(id);if err!=nil{http.Error(w,"server error",500);return};json.NewEncoder(w).Encode(map[string]string{"token":tok})
}
func (a *API) auctions(w http.ResponseWriter,r *http.Request){ if r.Method=="GET" { items,err:=a.Store.ListAuctions(r.Context()); if err!=nil { http.Error(w,"database error",500); return }; json.NewEncoder(w).Encode(items); return }; if r.Method!="POST"{w.WriteHeader(405);return}; var in struct{Title string `json:"title"`; StartingPrice int64 `json:"starting_price"`; EndsAt time.Time `json:"ends_at"`}; if json.NewDecoder(r.Body).Decode(&in)!=nil||in.Title==""||in.StartingPrice<0||in.EndsAt.Before(time.Now()){http.Error(w,"invalid auction",400);return}; x:=store.Auction{ID:uuid.NewString(),SellerID:auth.UserID(r.Context()),Title:in.Title,StartingPrice:in.StartingPrice,EndsAt:in.EndsAt}; if err:=a.Store.CreateAuction(r.Context(),x);err!=nil{http.Error(w,"database error",500);return}; json.NewEncoder(w).Encode(x)}
func (a *API) auction(w http.ResponseWriter,r *http.Request){ id:=strings.TrimPrefix(r.URL.Path,"/auctions/"); if strings.HasSuffix(id,"/bids") { id=strings.TrimSuffix(id,"/bids"); if r.Method!="GET" { w.WriteHeader(405); return }; bids,err:=a.Store.ListBids(r.Context(),id); if err!=nil { http.Error(w,"database error",500); return }; json.NewEncoder(w).Encode(bids); return }; if r.Method=="GET"{x,err:=a.Store.GetAuction(r.Context(),id);if err!=nil{http.NotFound(w,r);return};json.NewEncoder(w).Encode(x);return}; if r.Method!="POST"{w.WriteHeader(405);return}; var in struct{Amount int64 `json:"amount"`};if json.NewDecoder(r.Body).Decode(&in)!=nil||in.Amount<=0{http.Error(w,"invalid bid",400);return}; x,err:=a.Store.GetAuction(r.Context(),id);if err!=nil{http.NotFound(w,r);return};ok,err:=a.Bids.CheckAndSet(r.Context(),id,auth.UserID(r.Context()),in.Amount,x.CurrentPrice,x.EndsAt);if err!=nil{http.Error(w,"bid error",500);return};if !ok{http.Error(w,"bid rejected",409);return};newBid:=store.Bid{ID:uuid.NewString(),AuctionID:id,BidderID:auth.UserID(r.Context()),Amount:in.Amount};if err=a.Store.RecordBid(r.Context(),newBid);err!=nil{http.Error(w,"database error",500);return};if err=a.Store.UpdateCurrentPrice(r.Context(),id,in.Amount);err!=nil{http.Error(w,"database error",500);return};w.WriteHeader(201);json.NewEncoder(w).Encode(newBid)}
